server:
  port: 7003
spring:
  application:
    name: FUND

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlj?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 960314
eureka:
  client:
    service-url:
      defaultZone: http://10.12.155.82:7001/eureka
mybatis:
  mapper-locations: classpath:/mappers/*.xml



