server:
  port: 7002
spring:
  application:
    name: ZUUL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monmanager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
zuul:
  routes:
    USER: /user/**
    FUND: /fund/**
    FORUM: /forum/**
  sensitive-headers:
